### PR TITLE
Avoid more unnecessary task configuration

### PR DESCRIPTION
**Pull request by labkey-tchad**
#### Rationale
Making the build a bit snappier with more task configuration avoidance.
Before | After:
image

For future reference, `tasks.named('clean')` doesn't work for whatever reason.

#### Related Pull Requests
* N/A

#### Changes
* Replace `tasks.taskName` references with `tasks.named('taskName')`

### CODE REVIEW

**Review by labkey-susanh — COMMENTED** [review]
Thanks for doing this. You beat me to it.  I also have some shelved changes that replace some more `findByName` usages with `named`.  Mind if I add them in here?

**Comment by labkey-tchad** [comment]
> Thanks for doing this. You beat me to it. I also have some shelved changes that replace some more `findByName` usages with `named`. Mind if I add them in here?

Not at all.

**Review by labkey-susanh — COMMENTED** [review]
Looks like most of my changes were already done here.  We've got some additional work to do, I think with references to configurations, but I'll leave that for the time being.  Is there a server PR for testing these changes?

**Comment by labkey-tchad** [comment]
@labkey-susanh Getting a [build error](https://teamcity.labkey.org/buildConfiguration/bt312/2345348?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&logView=flowAware&showLog=2345348_575_283.299&logFilter=debug):
```
Caused by: groovy.lang.MissingPropertyException: No such property: project for class: org.labkey.gradle.plugin.FileModule
       at org.labkey.gradle.plugin.FileModule.addSourceSet(FileModule.groovy:96)
       at org.labkey.gradle.plugin.FileModule.apply(FileModule.groovy:69)
       at org.labkey.gradle.plugin.FileModule.apply(FileModule.groovy)
```

**Comment by labkey-susanh** [comment]
> @labkey-susanh Getting a [build error](https://teamcity.labkey.org/buildConfiguration/bt312/2345348?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&logView=flowAware&showLog=2345348_575_283.299&logFilter=debug):
> 
> ```
> Caused by: groovy.lang.MissingPropertyException: No such property: project for class: org.labkey.gradle.plugin.FileModule
>        at org.labkey.gradle.plugin.FileModule.addSourceSet(FileModule.groovy:96)
>        at org.labkey.gradle.plugin.FileModule.apply(FileModule.groovy:69)
>        at org.labkey.gradle.plugin.FileModule.apply(FileModule.groovy)
> ```

Oops. Got too greedy.

**Comment by labkey-tchad** [comment]
Verifying on TeamCity: [DRT](https://teamcity.labkey.org/buildConfiguration/bt5/2346010), [Installers](https://teamcity.labkey.org/buildConfiguration/LabKey_Trunk_Premium_InstallersCustom/2346014)

**Review by labkey-susanh — APPROVED** [review]

**Pull request merged**
